trigger:
  batch: true
  branches:
    include: [ '*' ]
  tags:
    include: [ 'release/*/*' ]
pr:
  branches:
    include: [ 'main', 'release/*' ]

jobs:
- job: Windows
  pool:
    vmImage: VS2017-Win2016
  steps:
  - template: build/azure-pipelines/win32/build.yml

- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: build/azure-pipelines/linux/build.yml

- job: macOS
  pool:
    vmImage: macOS-latest
  steps:
  - template: build/azure-pipelines/darwin/build.yml
